language: c
compiler:
  - gcc
  - clang
  - i686-w64-mingw32-gcc

script: ./travis-ci-build.sh

before_install:
  - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y mingw32
  - sudo apt-get install -q -y libgl1-mesa-dev libsdl2-dev libvorbis-dev libfreetype6-dev mingw-w64

notifications:
  email: false
