language: cpp
sudo: required
dist: trusty

services:
   - docker

git:
    depth: 5

script:
    - ./travis-ci-build.sh

notifications:
    email:
      on_success: change
      on_failure: change

matrix:
  include: 
    - os: linux
      compiler: gcc
      before_install:
          - docker build -t wtfbbqhax/ioquake3:v1 .
          - docker run -v $(pwd)/build:/usr/src/build wtfbbqhax/ioquake3:v1 ./docker-build.sh

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: USE_CODEC_VORBIS=1 USE_FREETYPE=1 ARCH=x86_64
      before_install:
        - brew update
        - brew install freetype --universal
        - rm -rf build
