language: cpp
sudo: required
dist: trusty

services:
   - docker

git:
    depth: 5

script:
    - ./travis-ci-build.sh

notifications:
    email:
      on_success: change
      on_failure: change

matrix:
  include: 
    - os: linux
      env: PLATFORM=linux
      before_install:
      - docker pull wtfbbqhax/tremulous:v3
      - docker run -e PLATFORM -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./docker-build.sh
    - os: linux
      env: PLATFORM=mingw32
      before_install:
      - docker pull wtfbbqhax/tremulous:v3
      - docker run -e PLATFORM -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./docker-build.sh
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: USE_CODEC_VORBIS=1 USE_FREETYPE=1 ARCH=x86_64
      before_install:
        - brew update
        - brew install freetype --universal
        - rm -rf build
