
set(DEFAULT_BASEGAME "baseq3")
set(DEFAULT_MISSIONPACK "missionpack")

set(DEFAULT_USE_INTERNAL_LIBS TRUE)
set(DEFAULT_USE_RENDERER_DLOPEN TRUE)

set(DEFAULT_BUILD_STANDALONE FALSE)

#cmake is using CMAKE_INSTALL_PREFIX/DEFAULT_REL_INSTALL_DEST
set(DEFAULT_REL_INSTALL_DEST "games/quake3")
#install directories (COPYDIR) overwrite the relative installation destination
#set(DEFAULT_INSTALL_DIR "/usr/local/games/quake3")
#set(DEFAULT_BASEGAME_VM_INSTALL_DIR "/path/to/vm")
#set(DEFAULT_MISSIONPACK_VM_INSTALL_DIR "/path/to/vm")
#set(DEFAULT_BASEGAME_QVM_INSTALL_DIR "/path/to/vm")
#set(DEFAULT_MISSIONPACK_QVM_INSTALL_DIR "/path/to/vm")

set(DEFAULT_GENERATE_DEPENDENCIES TRUE)
set(DEFAULT_USE_AUTOUPDATER FALSE)
set(DEFAULT_AUTOUPDATER_BIN "autosyncerator")

#set(DEFAULT_BIN_EXT "")

#client and server
set(DEFAULT_VERSION "1.36")
set(DEFAULT_USE_GIT_REV TRUE)
#set(DEFAULT_BASEDIR "")

#client only
set(DEFAULT_CLIENT_BIN "ioquake3")
set(DEFAULT_USE_CODEC_OPUS TRUE)
set(DEFAULT_USE_CODEC_VORBIS FALSE)
set(DEFAULT_USE_CURL TRUE)
set(DEFAULT_USE_CURL_DLOPEN TRUE)
set(DEFAULT_USE_FREETYPE FALSE)
set(DEFAULT_USE_ICON TRUE)
set(DEFAULT_USE_MUMBLE TRUE)
set(DEFAULT_USE_OPENAL TRUE)
set(DEFAULT_USE_OPENAL_DLOPEN TRUE)
set(DEFAULT_USE_VOIP TRUE)

#server only
set(DEFAULT_SERVER_BIN "ioq3ded")

#main cmakelist only
set(DEFAULT_BUILD_BASEGAME TRUE)
set(DEFAULT_BUILD_CLIENT TRUE)
set(DEFAULT_BUILD_GAME_QVM TRUE)
set(DEFAULT_BUILD_GAME_VM TRUE) #native vm (so/dll)
set(DEFAULT_BUILD_MISSIONPACK TRUE)
set(DEFAULT_BUILD_RENDERER_OPENGL2 TRUE)
set(DEFAULT_BUILD_SERVER TRUE)

#cgame, game, ui
#Produce a qvm file compatible with Q3 1.32b
set(DEFAULT_VQ3_COMPATIBLE_QVM TRUE)

set(DEFAULT_NO_STRIP FALSE)
set(DEFAULT_BUILD_STATIC_CRT TRUE)
