if(USE_INTERNAL_SDL2)
    set(SDL2_DEFINES "-DUSE_LOCAL_HEADERS=1")
    set(SDL2_LIB_PREFIX "${CMAKE_SOURCE_DIR}/code/libs")
    set(SDL2_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/code/SDL2/include")
    if(APPLE)
        set(SDL2_LIBRARIES "-L${SDL2_LIB_PREFIX}/libs/macosx -lSDL2-2.0.0")
    elseif(WIN32)
        set(SDL2_LIBRARIES "-L${SDL2_LIB_PREFIX}/libs/win64 -lSDL2-2.0.0")
    endif()
else(USE_INTERNAL_SDL2)
    set(SDL2_PREFIX "/usr")
    if(APPLE)
        set(SDL2_PREFIX "/usr/local")
    endif(APPLE)
    set(SDL2_INCLUDE_DIRS "${SDL2_PREFIX}/include/SDL2")
    set(SDL2_LIBRARIES "-L${SDL2_PREFIX} -lSDL2")
endif(USE_INTERNAL_SDL2)
