name: Build
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Compile
      run: make release
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: build/*.zip
  windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: |
        choco install zip
        make release
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: build/*.zip
  macos:
    name: macOS
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make release
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v2
      with:
        name: macOS
        path: build/*.zip

  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - windows-2019
          - macos-10.15

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Dependencies (Linux)"
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - name: "Install Dependencies (OSX)"
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install sdl2

      - name: "Install Dependencies (Windows)"
        if: ${{ runner.os == 'Windows' }}
        run: choco install zip

      - name: "Compile"
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install
          cmake --build .
          cmake --install .
