name: "Build"
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-2019
          - macos-10.15
#          - macos-11.0
    env:
      ARCHIVE: 1

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Dependencies (Linux)"
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - name: "Install Dependencies (Windows)"
        if: ${{ runner.os == 'Windows' }}
        run: choco install zip

#      - name: "Install Dependencies (macOS)"
#        if: ${{ runner.os == 'macOS' }}
#        run: 

      - name: "Compile"
        run: make release

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: build/*.zip
